/** @type {import('@lingui/conf').LinguiConfig} */

const locales = [
  "be",
  "bg",
  "bn",
  "bs",
  "ca",
  "cs",
  "da",
  "de",
  "el",
  "en",
  "es",
  "et",
  "fi",
  "fil",
  "fr",
  "ga",
  "hi",
  "hr",
  "hu",
  "hy",
  "id",
  "is",
  "it",
  "ja",
  "jv",
  "ka",
  "kk",
  "km",
  "ko",
  "ks",
  "ky",
  "lb",
  "lt",
  "lv",
  "mk",
  "ml",
  "mn",
  "ms",
  "mt",
  "my",
  "ne",
  "nl",
  "no",
  "pa",
  "pl",
  "pt",
  "pt-BR",
  "ro",
  "ru",
  "sc",
  "sk",
  "sl",
  "sq",
  "sr",
  "sv",
  "ta",
  "th",
  "tk",
  "tr",
  "uk",
  "uz",
  "vi",
  "zh-Hans",
];

module.exports = {
  locales: locales,
  // pt-BR is a specialization of pt, not a separate translation effort: anything
  // not translated specifically for Brazil should read as Portuguese rather than
  // fall through to the English source. Lingui seeds fallbacks from CLDR parent
  // locales, but CLDR treats `pt` as Brazilian-default and lists no pt-* parents,
  // so this pairing has to be stated explicitly.
  fallbackLocales: {
    "pt-BR": "pt",
  },
  catalogs: [
    {
      path: "src/locales/{locale}/messages",
      // utils holds the share-card copy helpers (t(i18n) macro calls)
      include: ["./components", "./pages", "./utils"],
    },
  ],
  service: {
    name: "TranslationIO",
    apiKey: "7945437f43044617aa3eadaf0cb7e184",
  },
};
