/**
 * Per-request Lingui instances for server code (GSSP, API routes). The global
 * i18n singleton in utils/i18n.ts is fine for the client, but server renders
 * for different locales can overlap, so each request gets its own instance.
 *
 * Catalogs live in src/locales/{locale}/messages (generated by lingui
 * compile). Unknown locales and load failures fall back to English — share
 * meta and OG cards must never fail on locale problems.
 */
import { I18n, setupI18n } from "@lingui/core";

const LOCALE_PATTERN = /^[a-zA-Z]{2,3}(-[a-zA-Z]{2,8})?$/;

export const loadServerI18n = async (locale?: string | null): Promise<I18n> => {
  const requested =
    typeof locale === "string" && LOCALE_PATTERN.test(locale) ? locale : "en";
  try {
    const { messages } = await import(`../src/locales/${requested}/messages`);
    return setupI18n({
      locale: requested,
      messages: { [requested]: messages },
    });
  } catch {
    const { messages } = await import("../src/locales/en/messages");
    return setupI18n({ locale: "en", messages: { en: messages } });
  }
};
